---
title: "CC "
author: "Tiffany Sun (tsun28@amherst.edu)"
format: 
  pdf:
    toc: true
date: "`r Sys.Date()`"
editor: source
knitr:
  opts_chunk:
    fig.align: center
---

```{r}
#| label: packages
#| echo: FALSE
#| message: FALSE

knitr::opts_chunk$set(   
  message = FALSE)   

library(tidyverse)
library(vroom)
library(tidygeocoder)
library(maps)
library(ggrepel)
library(sf)

my_sf <- read_sf("UHF42.geo.json") |>
  janitor::clean_names()

```

```{r}
#| label: data
data <- vroom("Motor_Vehicle_Collisions_-_Crashes_20260612.csv") |>
    janitor::clean_names() 

missing_coords <- data |>
    select(c(longitude, latitude, on_street_name)) |>
    filter(is.na(longitude) & is.na(latitude), !is.na(on_street_name)) |>
    select(on_street_name)

coords <- data |>
  select(c(longitude, latitude, number_of_persons_injured, number_of_persons_killed)) |>
  filter(!is.na(longitude), !is.na(latitude), latitude != 0, longitude != 0) |>
  mutate(longitude = ifelse(longitude < -200, yes =longitude + 127.2832727, longitude))
  
```

```{r}
#| label: map

ggplot(my_sf) +
  geom_sf(fill = "white", color = "black", linewidth = 0.1) +
  theme_void()

data_sf <- st_as_sf(
  coords,
  coords = c("longitude", "latitude"),
  crs = 4326
) |>
  st_make_valid()

 data_sf <- st_transform(data_sf, st_crs(my_sf))

  st_crs(data_sf)
  st_crs(my_sf)


counts <- lengths(st_intersects(my_sf, data_sf))

joined <- st_intersection(my_sf, data_sf)

my_sf$n <- counts

  ggplot(my_sf) +
  geom_sf(aes(fill = n), color = "black", linewidth = 0.1) +
  theme_void()

geom_sf()

```

```{r}
#| label: analysis

# Top ten neighborhoods with most vehicle collisions
my_sf |>
  mutate(my_sf, geoname = fct_reorder(geoname, n)) |>
  arrange(desc(n)) |>
  slice(1:10) |>
  ggplot(
    aes(geoname, n)
  ) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Top Ten Neighborhoods with Most Vehicle Collisions",
    y = "Neighborhoods",
    x = "Collisions"
  )


# Boroughs with most vehicle collisons
my_sf |>
  filter(
    borough != "N/A"
  ) |>
  group_by(borough) |>
  summarize(
    ct = sum(n)
  ) |>
  mutate(borough = fct_reorder(borough, ct)) |>
  arrange(desc(ct)) |>
  slice(1:10) |>
  ggplot(
    aes(borough, ct)
  ) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Ranked Boroughs with Most Vehicles Collisions",
    y = "Borough",
    x = "Collisions"
  )

  # Casualties

```

```{r}
#| label: handling missing data 
n <- ceiling(nrow(missing_coords) / 10000)

ds <- split(missing_coords, factor(sort(rank(row.names(missing_coords))%%n)))

census_records <- data.frame()

ds <- lapply(ds, function(d) {
  as.data.frame(d) |>
    mutate(on_street_name = paste0(on_street_name, ", NY")) |>
    geocode(
      address = on_street_name,
      method = "census",
      lat = "latitude",
      long = "longitude"
    )
})

 ds <- bind_rows(ds) |>
  filter(is.na(latitude))

 census_records <- bind_rows(ds) |>
  filter(!is.na(latitude)) 

census_records$on_street_name <- census_records$on_street__name |> str_remove(", NY")
  


```

